// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDEDVgFTrPn_z4FIystimK0xxGMJ7CcGw',
    appId: '1:1011640211437:web:bdb5c278342a958336f9e4',
    messagingSenderId: '1011640211437',
    projectId: 'projectmobile-9da55',
    authDomain: 'projectmobile-9da55.firebaseapp.com',
    storageBucket: 'projectmobile-9da55.firebasestorage.app',
    measurementId: 'G-Z03CMHXJGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1a4G35-pWBeRlWT7dWMddEPGbt_j0IFE',
    appId: '1:1011640211437:android:a7efeab77a479f0036f9e4',
    messagingSenderId: '1011640211437',
    projectId: 'projectmobile-9da55',
    storageBucket: 'projectmobile-9da55.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDEDVgFTrPn_z4FIystimK0xxGMJ7CcGw',
    appId: '1:1011640211437:web:18628db26a09af3936f9e4',
    messagingSenderId: '1011640211437',
    projectId: 'projectmobile-9da55',
    authDomain: 'projectmobile-9da55.firebaseapp.com',
    storageBucket: 'projectmobile-9da55.firebasestorage.app',
    measurementId: 'G-HSDR25VM4Q',
  );

}